services:
  tlsod:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: darknet_ehf/tlsod:0.6.0
    container_name: tlsod
    hostname: tlsod
    restart: unless-stopped
    volumes:
      - tlsod_db:/data
    networks:
      - darknet

volumes:
  tlsod_db:

networks:
  darknet:
    external: true
